### PR TITLE
Adding better support for untyped edge creation.

### PR DESCRIPTION
**Pull request by mohataher**
Instead of returning just plain untyped edge, I framed it to the return type of the calling method.

`return thiz.getGraph().addFramedEdge(newVertex, thiz, label, method.getReturnType());`
Instead of
`return thiz.getGraph().addFramedEdge(newVertex, thiz, label);`

For diving deeper into details, please view thread here
http://bugs.syncleus.com/browse/FMA-67

### CODE REVIEW

**Comment by freemo** [comment]
@mohataher  Thanks so much, I will review this further. Please keep in mind while GitHub pull requests are totally valid way of submitting patches, our official method is through gerrit and will often get you much quicker turn-over time on my part. For more information see: http://wiki.syncleus.com/index.php/Ferma:Contributing

**Comment by freemo** [comment]
@mohataher  Very first thing I noticed is that this pull request has several undesired files int he commit, things like .classpath and .settings. Please add these to gitignore and remove them from the commits (simply making a new commit that deletes them wont be enough you will have to rebase, since removing them in a new commit would still get them into our history).

**Comment by freemo** [comment]
@mohataher Also don't forget to add yourself as a contributor (CONTRIBUTORS.md and the pom.xml both have places for this).

**Comment by mohataher** [comment]
Alright. I will try my best using gerrit next times.

All files removed in the last commit. It's strange how they were pushed even though they were in the gitignore.

Magically (mostly thanks to you), my name was in contributors and pom.xml. I updated it as well.

**Comment by freemo** [comment]
@mohataher  Just noticed this pull request was still outstanding. did we resolve this through a different branch or something?

**Comment by freemo** [comment]
@mohataher we've implemented this through other means. so going to close this but thanks for your contribution. I've gone ahead and updated your change int he contributors file however.

**Pull request closed without merging**
