### PR TITLE
add information about support JanusGraph

### PR DESCRIPTION
**Pull request by trojek**

### CODE REVIEW

**Comment by freemo** [comment]
@trojek have you actually tested against janus graph (titan and oirientDB needed some minor fixes to make it compatible). Also, if it has been tested do you have any example projects or unit tests you could add to demonstrate that? Or at the very least perhaps you could add a short page to the documentation that shows how to use Ferma with janus graph. I think that would go a long way to building some confidence around the compatibility and even help more people make the choice to adopt it as their back end.

Neither I or any of our team members (that I know of) have tried Ferma with Janus yet.

**Comment by trojek** [comment]
I just did sample "hello world" application with JanusGraph, so I can't say that I have tested it. If Titan needs some minor fixes I assume that JanusGraph will not be fully compatible. Especially taking into account that JanusGraph uses numerous storage backend.
I think that for now, you can cancel this pull request. I will do further research and if I will prepare some reasonable examples and docs I will pull request.

**Comment by freemo** [comment]
@trojek Can you send me a link to the Hello World example you currently have going. That might be enough for me honestly. I also dont mind taking it and adding it to either our unit tests or our documentation. So might not need more than that honestly.

The fixes for titan were actually very minor, and unrelated to the multiple backends (look at our titan branch). It really was just because titan threw some runtime exceptions on a next() that is a slightly different behavior than with other databases. It was so minor i wouldnt expect it to be an issue with Janus. The only point is that there can sometimes be very specific oddities, usually minor, with this sort of stuff that deserves a working basic example to show compatibility. Chances are Janus might "just work" but lets run an example to make sure is all.

I think if your trying to promote Janus a bit it will be good for you guys to have an example app or a place in our docs anyway which is more likely to help you guys get some users than just a bullet point in readme anyway. So win-win.

I'll close this out for now but if you can get a basic hello world example up that does some of the basic operations and either add that to our docs or even just share it with me so i can verify it works I'd be more than happy to add janus to our read me. If you send me the link I can review and it may be enough as is.

**Comment by evillasr** [comment]
I just did the hello World with Janus. Is it steal needed ? 
I can upload it with a simple description

**Comment by freemo** [comment]
@evillasr I think that would be good enough. Could you document for us the steps needed with maven to get hello world working with janus graph? I can add that to our documentation and therefore officially add support for it in our readme as well.

**Comment by evillasr** [comment]
Here you have a Demo with the quick start working properly 😸  🚀 
https://github.com/evillasr/ferma-demo here it is 👍 

Let me know if I can help in any other way

**Comment by evillasr** [comment]
Is there something else to do in order to complete the documentation update 🚀  maybe I can help 😍

**Comment by evillasr** [comment]
Tell me if it works and I can do the same demo with Thinkerpop 3 that is sopported as well 🚀

**Comment by freemo** [comment]
@evillasr thanks so much, ill approve now.

**Pull request merged**
