### PR TITLE
Add has(Class<?> clazz) shortcut method

### PR DESCRIPTION
**Pull request by Jotschi**

### CODE REVIEW

**Comment by freemo** [comment]
Oh I like this. For consistency purposes would it be possible to also add an hasNot varient of this?

**Comment by Jotschi** [comment]
Sure, i'll add it.

**Comment by Jotschi** [comment]
@freemo I added the change. I don't know whether a force push actually invokes a github notification.

**Comment by freemo** [comment]
@Jotschi  Wonderful! thanks. I will check into it. We usually use gerrit rather than pull requests, but pull requests are accepted too :)

**Comment by freemo** [comment]
@Jotschi So i spent a bit more time looking into this. The way it is currently written it relies on the default type resolution key rather than the actual one. It would fail if custom key names were used. Might want to consider adding a getter to the PolymorphicTypeResolver for the typeResolutionKey and access that instead.

**Comment by freemo** [comment]
@Jotschi Wow I had a major stupid moment on this one... I just realized most of this feature was already implemented check out PolymorphicTypeResolver.hasType, that is the whole point I created it. I do however like that we couple this into the gremlin pipeline as you are attempting to do. So I recommend instead you create a notHasType() method in the resolver as well and then use these in the gremlin pipeline instead of what you are doing now.

**Comment by Jotschi** [comment]
Yes, you are right. I did not notice that method. Unfortunately the methods are only accepting VertexTraversal / EdgeTraversals. But i have a gremlinpipeline at hand. Any suggestions on how to get the traversal from the pipeline? I could in any case enhance the TypeResolver interface and add a method that checks hasType / hasNotType using GremlinPipelines.

```
The method hasType(VertexTraversal<?,?,?>, Class<?>) in the type TypeResolver is not applicable for the arguments (FermaGremlinPipeline, Class<capture#11-of ?>)
```

**Comment by freemo** [comment]
Well you are trying to add "hasType" and "hasNotType" to the EdgeTraversal and VertexTraversal classes (or rather their associated concrete classes).. So you should be able to use the methods as is.. just do something like this from within your method definition:

return typeResolver.hasType(this, theClass);

**Comment by Jotschi** [comment]
@freemo I update the PR and added a bugfix for a minor error that i encountered while using Ferma with blueprint neo4j2

**Comment by freemo** [comment]
@Jotschi This PR has been merged. Thank you for your contribution.

**Pull request merged**
